# Generated by Django 5.2.1 on 2025-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('challenge_text', models.TextField(verbose_name='The Challenge')),
                ('solution_text', models.TextField(verbose_name='The Solution')),
                ('impact_text', models.TextField(verbose_name='The Impact')),
            ],
        ),
    ]
