# Generated by Django 5.2.1 on 2025-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('uiux', 'UI/UX Designer'), ('developer', 'Web Developer'), ('marketing', 'Marketing Executive'), ('designer', 'Graphic Designer'), ('civil_engineer', 'Civil Engineer'), ('site_manager', 'Site Manager'), ('project_manager', 'Project Manager')], max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
