# Generated by Django 5.2.1 on 2025-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('category', models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent'), ('business', 'Business'), ('trending', 'Trending'), ('top', 'Top'), ('searched', 'Most Searched')], max_length=20)),
                ('link', models.URLField(blank=True, help_text='Paste full URL including https://', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
