# Generated by Django 5.2.1 on 2025-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('category', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Recent', 'Recent')], max_length=20)),
            ],
        ),
    ]
