# Generated by Django 5.2.1 on 2025-07-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
