# Generated by Django 5.2.1 on 2025-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_remove_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], max_length=10)),
                ('channels', models.CharField(max_length=100)),
                ('alert_types', models.CharField(max_length=255)),
                ('timing', models.CharField(choices=[('immediate', 'Immediately as they happen'), ('daily', 'Daily Summary'), ('limited', 'Only during certain hours')], max_length=20)),
                ('specific_hours', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
