# Generated by Django 5.2.1 on 2025-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0008_alertregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('alert_type', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
