# Generated by Django 5.2.1 on 2025-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0010_estimatecategory_estimateimagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
