# Generated by Django 5.2.1 on 2025-07-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0011_estimatecategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed-Use')], max_length=50)),
                ('base_rate', models.PositiveIntegerField()),
                ('green_feature_cost', models.PositiveIntegerField(default=50000)),
                ('design_percentage', models.FloatField(default=10.0)),
                ('permit_cost', models.PositiveIntegerField(default=50000)),
            ],
        ),
    ]
