from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
path('admin/', admin.site.urls),
path('',views.indexpage,name='indexpage'),
path('about',views.about,name='about'),
path('home',views.home,name='home'),
path('expertise',views.expertise,name='expertise'),
path('projects',views.projects,name='projects'),
path('digital',views.digital,name='digital'),
path('insights',views.insights,name='insights'),
path('contact',views.contact,name='contact'),
path('contact_view',views.contact_view,name='contact_view'),
path('careers',views.careers,name='careers'),
path('job_application',views.job_application,name='job_application'),
path('investors',views.investors,name='investors'),
path('news',views.news,name='news'),
path('events',views.events,name='events'),
path('company_profile',views.company_profile,name='company_profile'),
path('news/<int:news_id>/', views.news_detail, name='news_detail'),
path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
path('leadership',views.leadership,name='leadership'),
path('eco',views.eco,name='eco'),
path('awards',views.awards,name='awards'),
path('Business_Practice',views.Business_Practice,name='Business_Practice'),
path('governance',views.governance,name='governance'),
path('estimate/<str:category>/',views.estimate,name='estimate'),
path('submit_alert',views.alert_form_view,name='submit_alert'),
path('insight_detail',views.insight_detail,name='insight_detail'),
path('insights/<int:blog_id>/', views.insights_detail, name='insights_detail'),
path('mobility',views.mobility,name='mobility'),
path('climatechange',views.climatechange,name='climatechange'),
path('connectedhighway',views.connectedhighway,name='connectedhighway'),
path('energy',views.energy,name='energy'),
path('places',views.places,name='places'),
path('resilience',views.resilience,name='resilience'),
path('restoration',views.restoration,name='restoration'),
path('urbanism',views.urbanism,name='urbanism'),
path('asset',views.asset,name='asset'),
path('contract',views.contract,name='contract'),
path('design',views.design,name='design'),
path('business',views.business,name='business'),
path('architecture',views.architecture,name='architecture'),
path('prog',views.prog,name='prog'),
path('commercials',views.commercials,name='commercials'),
path('health',views.health,name='health'),
path('privacy',views.privacy,name='privacy'),
path('aerospace',views.aerospace,name='aerospace'),
path('automotive',views.automotive,name='automotive'),
path('chemical',views.chemical,name='chemical'),
path('commercial_dev',views.commercial_dev,name='commercial_dev'),
path('contractors',views.contractors,name='contractors'),
path('power',views.power,name='power'),
path("submit-feedback/", views.submit_feedback, name="submit_feedback"),
path("submit-issue/", views.submit_issue, name="submit_issue"),
]